#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

layout (std430, set = 0, binding = 0) readonly buffer TilesSum {
    uint prefixSum[];
};
layout (std430, set = 0, binding = 1) readonly buffer Depths {
    float depths[];
};
layout (std430, set = 0, binding = 2) readonly buffer Radii {
    int radius[];
};
layout (std430, set = 0, binding = 3) readonly buffer BoundingBox {
    uvec4 boundingBox[];  // x,y,z,w = min_x, min_y, max_x, max_y
};
layout (std430, set = 0, binding = 4) writeonly buffer OutKeys {
    uint64_t keysUnsorted[];
};
layout (std430, set = 0, binding = 5) writeonly buffer OutPayloads {
    uint valuesUnsorted[];
};

layout(push_constant) uniform Constants
{
    uint tileX;
    int nGauss;
    uint culling;
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    // 这里的 index 拿的是全局的，和 dispatch 中的参数是有关的
    if (index >= nGauss) {
        return;
    }
    // nGauss 应该是指 具体有多少 并不总是为 256 之类的整数


    // 这里如果半径为零 或者 有一个全局的删减标志，那就直接返回
    if (radius[index] == 0 && culling == 1) {
        return;
    }

    uvec4 aabb = boundingBox[index]; // 拿到包围盒,应该是 包围盒的最大值和最小值
    uint vector_size = (index == 0 ? 0 : prefixSum[index - 1]); // prefix 是前缀的意思
    // 如果 全局是零，那么还是 零
    // 如果 全局不为零，那么 我需要 知道 每个分配的 vector 的 区域的起始地址是多少
    // 那么也就是 keysUnsorted valuesUnsorted 这两个点内存区域会很大
    // 另一个一个原因是并行的，没有办法 一个跑完再跑另一个
    // 如果没有的默认值是多少呢？
    // 有办法将每个 group 算法的想办法合并在一起吗？
    // prefixSum 是 之前计算完成的结果，前缀和 ，每个位置存储的是 之前全部位置的总和
    for (uint i = aabb.x; i < aabb.z; i++) {
        for (uint j = aabb.y; j < aabb.w; j++) {
            uint64_t tileIndex = i + j * tileX; // tileX 猜测每行 有多少个像素
            uint depthBits = floatBitsToUint(depths[index]);
            uint64_t key = (tileIndex << 32) | uint64_t(depthBits);
            // key 只是一个简单的偏移，并没有使用 莫顿码之类的转换
            keysUnsorted[vector_size] = key;
            valuesUnsorted[vector_size] = index;
            // 上面两个我大致 知道是什么意思，
            // key 放入，之后 进行排序
            vector_size++;
        }
    }
}