#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_buffer_reference: require
#extension GL_EXT_scalar_block_layout: require
#extension GL_ARB_gpu_shader_int64: require

layout (std430, buffer_reference, scalar) readonly buffer TilesSum_struct {
    uint prefixSum[];
};
layout (std430, buffer_reference, scalar) readonly buffer Depths_struct {
    float depths[];
};
layout (std430, buffer_reference, scalar) readonly buffer Radii_struct {
    int radius[];
};
layout (std430, buffer_reference, scalar) readonly buffer BoundingBox_struct {
    uvec4 boundingBox[];  // x,y,z,w = min_x, min_y, max_x, max_y
};
layout (std430, buffer_reference, scalar) writeonly buffer OutKeys_struct {
    uint64_t keysUnsorted[];
};
layout (std430, buffer_reference, scalar) writeonly buffer OutPayloads_struct {
    uint valuesUnsorted[];
};

layout(push_constant) uniform Constants
{
    uint tileX;
    int nGauss;
    uint culling;
    uint64_t TilesSum_Address;
    uint64_t Depths_Address;
    uint64_t Radii_Address;
    uint64_t BoundingBox_Address;
    uint64_t OutKeys_Address;
    uint64_t OutPayloads_Address;
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    TilesSum_struct TilesSum = TilesSum_struct(TilesSum_Address);
    Depths_struct Depths = Depths_struct(Depths_Address);
    Radii_struct Radii = Radii_struct(Radii_Address);
    BoundingBox_struct BoundingBox = BoundingBox_struct(TilesSum_Address);
    OutKeys_struct OutKeys = OutKeys_struct(BoundingBox_Address);
    OutPayloads_struct OutPayloads = OutPayloads_struct(OutKeys_Address);


    uint index = gl_GlobalInvocationID.x;
    // 这里的 index 拿的是全局的，和 dispatch 中的参数是有关的
    if (index >= nGauss) {
        return;
    }
    // nGauss 应该是指 具体有多少 并不总是为 256 之类的整数


    // 这里如果半径为零 或者 有一个全局的删减标志，那就直接返回
    if (Radii.radius[index] == 0 && culling == 1) {
        return;
    }

    uvec4 aabb = BoundingBox.boundingBox[index]; // 拿到包围盒,应该是 包围盒的最大值和最小值
    uint vector_size = (index == 0 ? 0 : TilesSum.prefixSum[index - 1]); // prefix 是前缀的意思
    // 如果 全局是零，那么还是 零
    // 如果 全局不为零，那么 我需要 知道 每个分配的 vector 的 区域的起始地址是多少
    // 那么也就是 keysUnsorted valuesUnsorted 这两个点内存区域会很大
    // 另一个一个原因是并行的，没有办法 一个跑完再跑另一个
    // 如果没有的默认值是多少呢？
    // 有办法将每个 group 算法的想办法合并在一起吗？V
    // prefixSum 是 之前计算完成的结果，前缀和 ，每个位置存储的是 之前全部位置的总和
    for (uint i = aabb.x; i < aabb.z; i++) {
        for (uint j = aabb.y; j < aabb.w; j++) {
            uint64_t tileIndex = i + j * tileX; // tileX 猜测每行 有多少个像素
            uint depthBits = floatBitsToUint(Depths.depths[index]);
            uint64_t key = (tileIndex << 32) | uint64_t(depthBits);
            // key 只是一个简单的偏移，并没有使用 莫顿码之类的转换
            OutKeys.keysUnsorted[vector_size] = key;
            OutPayloads.valuesUnsorted[vector_size] = index;
            // 上面两个我大致 知道是什么意思，
            // key 放入，之后 进行排序
            vector_size++;
        }
    }
}