#version 450

#extension GL_EXT_buffer_reference: require
#extension GL_EXT_scalar_block_layout: require
#extension GL_ARB_gpu_shader_int64: require


layout (buffer_reference, scalar)  buffer Buffer_A_struct {
    uint buffer_a[];
};

layout (buffer_reference, scalar) buffer Buffer_B_struct {
    uint buffer_b[];
};


layout(push_constant) uniform Constants {
    uint64_t buffer_A_Address;
    uint64_t buffer_B_Address;
    uint step;
    uint numElements;
    uint readFromA;
// readFromA 最后一个是为
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;


void main() {
    Buffer_A_struct BufferA = Buffer_A_struct(buffer_A_Address);
    Buffer_B_struct BufferB = Buffer_B_struct(buffer_B_Address);

    uint index = gl_GlobalInvocationID.x;

    if (index >= numElements) {
        return;
    }

    uint stride = 1u << step;
    // 如果你输入一个数组：[1, 1, 1, 1, 1]
    // 通过改变 step（stride 每次翻倍：1, 2, 4, 8...）
    // 进行多轮迭代后，它最终会将数组转换为每个位置之前所有元素的累加和：
    // [1, 2, 3, 4, 5]

    uint value;
    if (readFromA == 1) {
        value = BufferA.buffer_a[index];
        if (index >= stride) {
            value = BufferA.buffer_a[index] + BufferA.buffer_a[index - stride]; // 这样更改看起来更加直观
        }
        BufferB.buffer_b[index] = value; // 总是将A的后半部分 与 前半部分相加，之后 在 保存在 对应的 B 的索引中
    } else {
        value = BufferB.buffer_b[index];
        if (index >= stride) {
            value = BufferB.buffer_b[index] + BufferB.buffer_b[index - stride];
        }
        BufferA.buffer_a[index] = value;
    }
}