#version 430 core

// 8x8 的二维线程块
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D input_texture; // 较高分辨率的输入
layout(binding = 1, rgba32f) uniform writeonly image2D OutputImage; // 减半分辨率的输出

void main()
{
    ivec2 image_size = imageSize(OutputImage);
    ivec2 outCoord = ivec2(gl_GlobalInvocationID.xy);

    if (outCoord.x >= image_size.x || outCoord.y >= image_size.y)
    return;

    // 计算当前输出像素在输入纹理中对应的归一化 UV 坐标
    vec2 texelSize = 1.0 / vec2(textureSize(input_texture, 0));
    vec2 uv = (vec2(outCoord) + vec2(0.5)) * 2.0 * texelSize;

    float x = texelSize.x;
    float y = texelSize.y;

    // 执行 13-tap 采样，利用硬件双线性插值获取平滑的下采样结果
    vec3 a = texture(input_texture, uv + vec2(-2*x,  2*y)).rgb;
    vec3 b = texture(input_texture, uv + vec2(   0,  2*y)).rgb;
    vec3 c = texture(input_texture, uv + vec2( 2*x,  2*y)).rgb;
    vec3 d = texture(input_texture, uv + vec2(-2*x,    0)).rgb;
    vec3 e = texture(input_texture, uv + vec2(   0,    0)).rgb;
    vec3 f = texture(input_texture, uv + vec2( 2*x,    0)).rgb;
    vec3 g = texture(input_texture, uv + vec2(-2*x, -2*y)).rgb;
    vec3 h = texture(input_texture, uv + vec2(   0, -2*y)).rgb;
    vec3 i = texture(input_texture, uv + vec2( 2*x, -2*y)).rgb;
    vec3 j = texture(input_texture, uv + vec2(  -x,    y)).rgb;
    vec3 k = texture(input_texture, uv + vec2(   x,    y)).rgb;
    vec3 l = texture(input_texture, uv + vec2(  -x,   -y)).rgb;
    vec3 m = texture(input_texture, uv + vec2(   x,   -y)).rgb;

    // 形状更接近圆形扩散。它通过中、外层正方形的错位叠加，打破了正方形的边界感。
    // 放大回屏幕时，光晕（Glow/Glint）是完美的圆形渐变扩散

    // 经典 13-tap 加权平均系数
    vec3 result = e * 0.125;
    result += (a + c + g + i) * 0.03125;
    result += (b + d + f + h) * 0.0625;
    result += (j + k + l + m) * 0.125;

    imageStore(OutputImage, outCoord, vec4(result, 1.0));
}
