//
// Created by 潘鑫 on 2025/12/5.
//

#ifndef HELLO_MAC_EIGHT_DIRECTION_DISCRETE_ORIENTATION_POLYTOPE_H
#define HELLO_MAC_EIGHT_DIRECTION_DISCRETE_ORIENTATION_POLYTOPE_H

#endif //HELLO_MAC_EIGHT_DIRECTION_DISCRETE_ORIENTATION_POLYTOPE_H