#version 450
#extension GL_GOOGLE_include_directive: enable
#include "tone_mapping.glsl"



layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout (set = 2, binding = 0) uniform sampler2D input_texture;
layout(rgba16f, set = 2, binding = 1) uniform image2D output_texture;



void main() {
    ivec2 image_size = imageSize(output_texture);
    if (gl_GlobalInvocationID.x >= image_size.x || gl_GlobalInvocationID.y >= image_size.y) {
        return;
    }
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / image_size;

    vec4 final_color = vec4(textureLod(materialParams_colorBuffer, uv, 0.0).rgb, 1.0);


    if (materialParams.bloom.x > 0.0) {
        vec3 bloomColor = textureLod(input_texture, uv, 0.0).rgb;
        final_color += bloomColor * materialParams.bloom.x;
    }

    // 这里基本上就已经算是写出了 怎么融合 bloom 的算法
    // 那么其实就是另一个问题了, bloom 应该如何执行 下采样 和 上采样的

    imageStore(output_texture, pixel_coords, final_color);
}
