#version 450
#extension GL_GOOGLE_include_directive: enable


#define EIGEN_INDEX(m, row, col) (m)[col][row]
#include "ssaoUtils.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout(set = 0, binding = 0) uniform sampler2D input_texture;
layout(rgba8, set = 0, binding = 1) uniform image2D output_texture;

layout (push_constant) uniform PushConstant
{
    vec2 axis;
    int  sampleCount;
    float farPlaneOverEdgeDistance; // 只有 用于下面的一个 函数
    float kernel[16];
}materialParams;

// 参数不多, 看看怎么做

float bilateralWeight(in highp float center_depth, in highp float sampleDepth) {
    // 问题是, farPlaneOverEdgeDistance 这个参数是什么意思? 用于比较什么?
    // 还是只是一个 进行比较的 缩放参数
    float diff = (sampleDepth - center_depth) * materialParams.farPlaneOverEdgeDistance;
    return max(0.0, 1.0 - diff * diff);
}

void tap(const highp sampler2D saoTexture,
        inout float sum, inout float totalWeight, float weight, float center_depth, vec2 position) {
    // ambient occlusion sample
    vec3 data = textureLod(saoTexture, position, 0.0).rgb;

    // bilateral sample
    float bilateral = weight * bilateralWeight(center_depth, unpack(data.gb));
    sum += data.r * bilateral;
    totalWeight += bilateral;
}



void main()
{
    if (gl_GlobalInvocationID.x >= imageSize(output_texture).x ||
        gl_GlobalInvocationID.y >= imageSize(output_texture).y) {
        return;
    }

    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = (vec2(pixel_coords) + 0.5) / imageSize(output_texture);


    vec3 data = textureLod(input_texture, uv, 0.0).rgb;
    if (data.g * data.b == 1.0) {
        // This is the skybox, skip
        imageStore(output_texture, pixel_coords, vec4(data, 0.0));
        return;
    }

    // we handle the center pixel separately because it doesn't participate in
    // bilateral filtering
    float center_depth = unpack(data.gb);
    // 这里我拿到的深度 是 ?
    float totalWeight = materialParams.kernel[0];
    float sum = data.r * totalWeight;

    vec2 offset = materialParams.axis;
    for (int i = 1; i < materialParams.sampleCount; i++) {
        float weight = materialParams.kernel[i];
        tap(input_texture, sum, totalWeight, weight, center_depth, uv + offset);
        tap(input_texture, sum, totalWeight, weight, center_depth, uv - offset);
        offset += materialParams.axis;
    }

    float ao = sum * (1.0 / totalWeight);

    imageStore(output_texture, pixel_coords, vec4(ao, data.gb, 0.0));
}
