#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (r8, set = 0, binding = 0) uniform image2D input_texture;
layout (r8, set = 0, binding = 1) uniform image2D out_texture;

void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    // 以 global_SSAO 为输出, 以输出 的 大小,转换出应该采样的 UV
    ivec2 texSize = imageSize(out_texture);
    uint width = uint(texSize.x);
    uint height = uint(texSize.y);
    // 越界检查
    if (x >= width || y >= height) {
        return;
    }
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);

    const int blurRange = 2;
    int n = 0;
    float result = 0.0;

    for (int offset_x = -blurRange; offset_x <= blurRange; offset_x++)
    {
        for (int offset_y = -blurRange; offset_y <= blurRange; offset_y++)
        {
            ivec2 neighbor_coords = pixel_coords + ivec2(offset_x, offset_y);

            neighbor_coords = clamp(neighbor_coords, ivec2(0), texSize - ivec2(1));

            result += imageLoad(input_texture, neighbor_coords).r;
            n++;
        }
    }
    imageStore(out_texture, pixel_coords,
            vec4(result / (float(n)), 0.0, 0.0, 0.0));
}