#version 450
#extension GL_GOOGLE_include_directive: enable
#include "tone_mapping.glsl"

#extension GL_EXT_nonuniform_qualifier : enable

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout (set = 0, binding = 0) uniform sampler2D input_texture;
layout(r32f, set = 0, binding = 1) uniform image2D output_texture;


//layout(binding = 1, rg32f) uniform writeonly image2D HZBMipmaps[];



void main() {
    ivec2 texSize = imageSize(output_texture);
    if (gl_GlobalInvocationID.x >= texSize.x || gl_GlobalInvocationID.y >= texSize.y) {
        return;
    }
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / texSize;


    vec4 color = texture(input_texture, inUV);



//    imageStore(HZBMipmaps[mipLevel], mipPos, vec4(maxDepth, avgDepth, 0.0, 0.0));


    imageStore(output_texture, pixel_coords, color);
}
