#version 430 core
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
#extension GL_GOOGLE_include_directive: enable
#include "global_shader_common.glsl"


void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imgSize = imageSize(global_dof_result);

    if (texelCoord.x >= imgSize.x || texelCoord.y >= imgSize.y) return;

    vec4 sharpData = texelFetch(global_offscreen, texelCoord, 0);
    vec4 blurData = imageLoad(global_dof_BlurImg, texelCoord);

    float coc = blurData.a; // 从 Alpha 通道中提取刚才算好的 CoC 强度
    // 在清晰和模糊像素之间根据 CoC 混合出最终色彩
    vec3 finalColor = mix(sharpData.rgb, blurData.rgb, coc);
    imageStore(global_dof_result, texelCoord, vec4(finalColor, 1.0));
}
