#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D input_texture;
layout(set = 0, binding = 1) uniform sampler2D input_texture_depth;
layout(rgba16f, set = 0, binding = 2) writeonly uniform image2D output_texture;
layout(r8, set = 0, binding = 3) writeonly uniform image2D output_coc;
// rgba16f 可能不对, 需要改改

#extension GL_GOOGLE_include_directive: enable
#include "common_math.glsl"
#include "dof_Utils.glsl"


layout (push_constant) uniform PushConstant
{
    vec2 cocParams;
    vec2 cocClamp;
    vec2 texelSize;
}materialParams;




// Dual Filtering（双重滤波）的下采样（Downsampling）
void main() {
    // 越界检查
    if (gl_GlobalInvocationID.x >= imageSize(output_texture).x ||
        gl_GlobalInvocationID.y >= imageSize(output_texture).y) {
        return;
    }
    highp vec2 uv = (gl_GlobalInvocationID.xy + vec2(0.5)) / imageSize(output_texture).xy;


    // the source is guaranteed to be a multiple of two, so we know the bilinear weights are 0.25

    vec4 s01 = textureLodOffset(input_texture, uv, 0.0, ivec2(0, 1));
    vec4 s11 = textureLodOffset(input_texture, uv, 0.0, ivec2(1, 1));
    vec4 s10 = textureLodOffset(input_texture, uv, 0.0, ivec2(1, 0));
    vec4 s00 = textureLodOffset(input_texture, uv, 0.0, ivec2(0, 0));

    vec4 hdr;
    // fireflies/flickering filtering
    hdr[0] = 1.0 / (1.0 + max3(s01.rgb));
    hdr[1] = 1.0 / (1.0 + max3(s11.rgb));
    hdr[2] = 1.0 / (1.0 + max3(s10.rgb));
    hdr[3] = 1.0 / (1.0 + max3(s00.rgb));

    vec4 d;
    #if defined(FILAMENT_HAS_FEATURE_TEXTURE_GATHER)
    d = textureGather(input_texture_depth, uv, 0); // 01, 11, 10, 00
    #else
    d[0] = textureLodOffset(input_texture_depth, uv, 0.0, ivec2(0, 1)).r;
    d[1] = textureLodOffset(input_texture_depth, uv, 0.0, ivec2(1, 1)).r;
    d[2] = textureLodOffset(input_texture_depth, uv, 0.0, ivec2(1, 0)).r;
    d[3] = textureLodOffset(input_texture_depth, uv, 0.0, ivec2(0, 0)).r;
    #endif

    // Get the CoC radius of each four samples to downsample.
    // We multiply by 0.5 to convert from diameter to radius.
    vec4 c = getCOC(d, materialParams.cocParams) * 0.5;
    float outCoc = downsampleCoC(c);
    vec4 w = downsampleCocWeights(c, outCoc, 1.0) * hdr;
    vec4 outColor = (s01 * w[0] + s11 * w[1] + s10 * w[2] + s00 * w[3]) * rcp(dot(vec4(1.0), w));

    // Clamp to maximum allowable CoC radius.
    outCoc = clamp(outCoc, materialParams.cocClamp[0], materialParams.cocClamp[1]);

    // If CoC is less that 0.5 full resolution pixel, we clamp to 0, this will reduce
    // artifacts in the "in focus" area and allow us to skip more tiles trivially.
    if (abs(outCoc) < MAX_IN_FOCUS_COC) {
        outCoc = 0.0;
    }

    #if POST_PROCESS_OPAQUE
    // kill the work performed above
    outColor.a = 1.0;
    #endif


    imageStore(output_texture, ivec2(gl_GlobalInvocationID.xy), vec4(outColor));
    imageStore(output_coc, ivec2(gl_GlobalInvocationID.xy), vec4(outCoc, 0, 0, 0));
}
