#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D input_texture_cocMinMax;
layout(rg16f, set = 0, binding = 2) writeonly uniform image2D output_texture;
// rgba16f 可能不对, 需要改改


float max4(const vec4 f) {
    vec2 t = max(f.xy, f.zw);
    return max(t.x, t.y);
}

float min4(const vec4 f) {
    vec2 t = min(f.xy, f.zw);
    return min(t.x, t.y);
}

void main() {
    // 越界检查
    if (gl_GlobalInvocationID.x >= imageSize(output_texture).x ||
        gl_GlobalInvocationID.y >= imageSize(output_texture).y) {
        return;
    }
    highp vec2 uv = (gl_GlobalInvocationID.xy + vec2(0.5)) / imageSize(output_texture).xy;

    highp vec2 size = vec2(textureSize(input_texture_cocMinMax, 0));

    ivec2 i = ivec2(uv * size - 0.5);

    #if defined(FILAMENT_HAS_FEATURE_TEXTURE_GATHER)
    vec4 mi = textureGather(input_texture_cocMinMax, uv, 0); // 01, 11, 10, 00
    #else
    vec4 mi;
    mi[0] = texelFetchOffset(input_texture_cocMinMax, i, 0, ivec2(0, 1)).r;
    mi[1] = texelFetchOffset(input_texture_cocMinMax, i, 0, ivec2(1, 1)).r;
    mi[2] = texelFetchOffset(input_texture_cocMinMax, i, 0, ivec2(1, 0)).r;
    mi[3] = texelFetchOffset(input_texture_cocMinMax, i, 0, ivec2(0, 0)).r;
    #endif


    imageStore(output_texture, ivec2(gl_GlobalInvocationID.xy), vec4(min4(mi), max4(mi), 0, 0));
}
