#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D input_texture;
layout(rgba16f, set = 0, binding = 2) writeonly uniform image2D output_texture;
// rgba16f 可能不对, 需要改改



layout (push_constant) uniform PushConstant
{
    float level;
    vec2 aspectRatio;
    vec2 threshold;
    float chromaticAberration;
    float ghostCount;
    float ghostSpacing;
    float haloRadius;
    float haloThickness;
}materialParams;




float smoothstep01(const float t) {
    return t * t * (3.0 - 2.0 * t);
}

float ring(float x, const float c, const float r) {
    return 1.0 - smoothstep01(min(abs(x - c) / r, 1.0));
}

vec3 sampleColor(const vec2 uv) {
    // because we work on reduced resolution, we assume mediump uv is enough.
    float level = materialParams.level;
    float chromaticAberration = materialParams.chromaticAberration;
    // make sure to avoid divide-by-zero in normalize
    vec2 offset = normalize(0.5001 - uv) * chromaticAberration;
    return vec3(
            textureLod(input_texture, uv + offset, level).r,
            textureLod(input_texture, uv, level).g,
            textureLod(input_texture, uv - offset, level).b
    );
}

vec3 ghosts(const vec2 vertex_uv) {
    // because we work on reduced resolution, we assume mediump uv is enough.
    float ghostSpacing = materialParams.ghostSpacing;
    float ghostCount = materialParams.ghostCount;
    float threshold = materialParams.threshold.x;
    vec2 uv = 1.0 - vertex_uv;
    vec2 v = (0.5 - uv) * ghostSpacing;
    vec3 color = vec3(0.0);
    for (float i = 0.0; i < ghostCount; i += 1.0) {
        vec2 suv = fract(uv + v * i);
        vec3 s = sampleColor(suv);
        s = clamp(s - threshold, 0.0, 1.0);
        color += s;
    }
    return color;
}

vec3 halo(const vec2 uv) {
    float haloRadius = materialParams.haloRadius;
    float haloThickness = materialParams.haloThickness;
    float threshold = materialParams.threshold.y;
    vec2 aspectRatio = materialParams.aspectRatio;

    // make sure to avoid divide-by-zero in normalize
    vec2 v = vec2(0.5001) - uv;
    // handle aspect ratio
    v.x *= aspectRatio.x;
    v = normalize(v);
    v.x *= aspectRatio.y;

    vec3 s = sampleColor(uv + v * haloRadius);
    s = clamp(s - threshold, 0.0, 1.0);

    vec2 uvWeight = (uv - vec2(0.5, 0.0)) * vec2(aspectRatio.x, 1.0) + vec2(0.5, 0.0);
    float d = distance(uvWeight, vec2(0.5));
    float weight = ring(d, haloRadius, haloThickness);
    return s * weight;
}


void main() {
    // 越界检查
    if (gl_GlobalInvocationID.x >= imageSize(output_texture).x ||
        gl_GlobalInvocationID.y >= imageSize(output_texture).y) {
        return;
    }
    highp vec2 uv = (gl_GlobalInvocationID.xy + vec2(0.5)) / imageSize(output_texture).xy;

    vec3 color = vec3(0.0);
    if (materialParams.ghostCount > 0.0) {
        color += ghosts(uv);
    }
    if (materialParams.haloThickness > 0.0) {
        color += halo(uv);
    }
    imageStore(output_texture, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0));
}
