#version 450
#extension GL_GOOGLE_include_directive: enable
#include "global_shader_common.glsl"
#include "common_math.glsl"




#include "Fxaa3_11.h"


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout (set = 2, binding = 0) uniform sampler2D input_texture;
layout(rgba16f, set = 2, binding = 1) uniform image2D output_texture;



void main() {
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    vec2  texelSize = (1.0f / imageSize(output_texture));
    vec2 screen_size = textureSize(input_texture, 0);
    uint width = uint(imageSize(output_texture).x);
    uint height = uint(imageSize(output_texture).y);

    // 越界检查
    if (x >= width || y >= height) {
        return;
    }

    ivec2 pixelCoord = ivec2(x, y); // imageStore 使用 2D 向量作为坐标

    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / imageSize(output_texture);


    highp vec2 texelMaxCorner = inUV + texelSize * 0.5;
    highp vec2 texelMinCorner = inUV - texelSize * 0.5;

    vec4 color = fxaa(
            inUV,
            vec4(texelMinCorner, texelMaxCorner),
            input_texture,
            texelSize,                          // FxaaFloat4 fxaaConsoleRcpFrameOpt,
            2.0 * texelSize,                    // FxaaFloat4 fxaaConsoleRcpFrameOpt2,
            8.0,                                // FxaaFloat fxaaConsoleEdgeSharpness,
            #if defined(G3D_FXAA_PATCHES) && G3D_FXAA_PATCHES == 1
            0.08,                               // FxaaFloat fxaaConsoleEdgeThreshold,
            #else
            0.125,                              // FxaaFloat fxaaConsoleEdgeThreshold,
            #endif
            0.04                                // FxaaFloat fxaaConsoleEdgeThresholdMin
    );
    #if POST_PROCESS_OPAQUE
    color.a = 1.0;
    #endif

    // 4. 计算距离 (计算到相机的实际直线距离，或者只用深度 Z 轴距离)
    // 方案 A：直线距离（更真实）

    // 电影感/戏剧感（Cinematic）：Intensity = 0.4, Smoothness = 0.2
    // 暗角范围大，但极其温柔，视线自然聚焦在屏幕中央
    //    vec3 finalColor = apply_vignette(fxaa_result.rgb, inUV, camera_vignette_intensity, camera_vignette_smoothness);
    //    // 模拟胶片
    //    {
    //        float noise = get_noise_v2(uvec2(inUV * texSize), render_timeline);
    //        float grainShift = noise - 0.5; // 重映射到 [-0.5, 0.5]
    //
    //        float luma = dot(finalColor, vec3(0.2126, 0.7152, 0.0722));
    //        float lumaMask = 4.0 * luma * (1.0 - luma);
    //        lumaMask = clamp(lumaMask, 0.0, 1.0);
    //        float offset = film_grain_intensity * grainShift * lumaMask;
    //        finalColor = finalColor * (1.0 + offset);
    //    }

    // 场景原始渲染 -> 不透明度雾效 -> TAA -> 景深 -> 运动模糊 -> Bloom -> 镜头色差 -> 色调映射与色彩校正 -> Unsharp Mask -> 镜头暗角 -> 胶片颗粒 -> 最终输出
    // 场景原始渲染 -> 不透明度雾效 -> 景深  -> Bloom -> 镜头色差 -> 色调映射与色彩校正 -> 画面放大一倍 -> FXAA ->  Unsharp Mask -> 镜头暗角 -> 胶片颗粒 -> 最终输出
    // 场景原始渲染 -> 不透明度雾效 ->  Super Resolution -> Bloom -> 镜头色差 -> 色调映射与色彩校正 ->  Unsharp Mask -> 镜头暗角 -> 胶片颗粒 -> 最终输出
    // 场景原始渲染（HDR Color）
    // 不透明度雾效（Distance Fog） —— （我们之前写的 Compute 雾就在这里）

    // 景深（Depth of Field）绽放（Bloom）镜片炫光（Lens Flare）
    // 镜头色差（Chromatic Aberration） —— （在这里引入通道颜色位移）
    // 色调映射与色彩校正（Tone Mapping & Color Grading） —— （将 HDR 转换为 LDR）
    // 在现代电影级渲染管线（如 Filament、Unreal Engine 5、ACES）中，标准的做法是“先色彩校正，再色调映射”；并且色彩校正确实是在线性空间（或对数线性空间）中进行的。

    // FXAA / TAA（抗锯齿）/ Super Resolution  —— （在最终的 LDR 图像上平滑包括色差在内的所有边缘）

    // Unsharp Mask（反遮罩锐化/俗称“锐化”）
    // 必须放在后处理管线的极后期——通常在 TAA/FXAA（抗锯齿）之后，
    // 镜头暗角（Vignette）和胶片颗粒（Film Grain）之前

    // 镜头暗角（Vignette） ——（暗角对边缘平滑度没有影响，通常作为最外层罩子）
    // 胶片颗粒（Film Grain）
    // 最终输出（To Screen / Present）

    // 把放大放置在 色调映射（Tone Mapping）之后、FXAA 之前

    imageStore(output_texture, pixelCoord, vec4(color));
}
