#version 450
#extension GL_GOOGLE_include_directive: enable
#include "commom_function_and_struct.glsl"


#define texture2D(t, uv)              texture(t, uv)
#define texture2DLod(t, uv, lod)      textureLod(t, uv, lod)

#define FXAA_PC 1          // 声明当前是 PC 平台（非主机、非移动端）
#define FXAA_GLSL_130 1    // 声明使用现代 GLSL 语法
#define FXAA_QUALITY__PRESET 12 // 选择画质预设（12 是官方推荐的中高性价比画质）
#define FXAA_GREEN_AS_LUMA 1

// --- 第二步：引入 NVIDIA 官方头文件 ---
#include "Fxaa3_11.h"


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout (set = 0, binding = 0) uniform sampler2D input_texture;
layout(rgba8, set = 0, binding = 1) uniform image2D out_texture;



void main() {
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    ivec2 texSize = imageSize(out_texture);

    vec2 screen_size = textureSize(input_texture, 0);
    uint width = uint(texSize.x);
    uint height = uint(texSize.y);

    // 越界检查
    if (x >= width || y >= height) {
        return;
    }

    ivec2 pixelCoord = ivec2(x, y); // imageStore 使用 2D 向量作为坐标

    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / texSize;


    vec4 fxaa_result = FxaaPixelShader(
            inUV, // pos: 当前像素的 UV 坐标
            vec4(0.0), // fxaaConsolePosPos: 主机专用，PC 填 0
            input_texture, // tex: 绑定的纹理结构体
            input_texture, // fxaaConsole360TexLuma: 远古 Xbox360 专用，同上
            input_texture, // fxaaConsole360TexChroma: 同上
            1.0 / screen_size.xy, // fxaaQualityRcpFrame: 核心！1.0 / 屏幕分辨率
            vec4(0.0), // fxaaConsoleRcpFrameOpt: 主机专用，填 0
            vec4(0.0), // fxaaConsoleRcpFrameOpt2: 主机专用，填 0
            vec4(0.0), // fxaaConsole360RcpFrameOpt2: 主机专用，填 0
            0.75, // fxaaQualitySubpix: 子像素过滤程度 (0.0~1.0)
            0.166, // fxaaQualityEdgeThreshold: 边缘检测阈值
            0.0833, // fxaaQualityEdgeThresholdMin: 暗部裁剪阈值
            0.0, // fxaaConsoleEdgeSharpness: 主机专用
            0.0, // fxaaConsoleEdgeThreshold: 主机专用
            0.0, // fxaaConsoleEdgeThresholdMin: 主机专用
            vec4(0.0)                   // fxaaConsole360ConstDir: 主机专用
    );

    // 4. 计算距离 (计算到相机的实际直线距离，或者只用深度 Z 轴距离)
    // 方案 A：直线距离（更真实）

    // 电影感/戏剧感（Cinematic）：Intensity = 0.4, Smoothness = 0.2
    // 暗角范围大，但极其温柔，视线自然聚焦在屏幕中央
    vec3 finalColor = apply_vignette(fxaa_result.rgb, inUV, 0.4, 0.2);


    {
        float noise = get_noise_v2(uvec2(inUV * texSize), 4);
        float grainShift = noise - 0.5; // 重映射到 [-0.5, 0.5]

        float luma = dot(finalColor, vec3(0.2126, 0.7152, 0.0722));
        float lumaMask = 4.0 * luma * (1.0 - luma);
        lumaMask = clamp(lumaMask, 0.0, 1.0);
        float offset = 0.2f * grainShift * lumaMask;
        finalColor = finalColor * (1.0 + offset);
    }
    // 场景原始渲染（HDR Color）
    // 不透明度雾效（Distance Fog） —— （我们之前写的 Compute 雾就在这里）

    // 景深（Depth of Field）绽放（Bloom）镜片炫光（Lens Flare）
    // 镜头色差（Chromatic Aberration） —— （在这里引入通道颜色位移）
    // 色调映射与色彩校正（Tone Mapping & Color Grading） —— （将 HDR 转换为 LDR）

    // FXAA / TAA（抗锯齿）/ Super Resolution  —— （在最终的 LDR 图像上平滑包括色差在内的所有边缘）

    // Unsharp Mask（反遮罩锐化/俗称“锐化”）
    // 必须放在后处理管线的极后期——通常在 TAA/FXAA（抗锯齿）之后，
    // 镜头暗角（Vignette）和胶片颗粒（Film Grain）之前

    // 镜头暗角（Vignette） ——（暗角对边缘平滑度没有影响，通常作为最外层罩子）
    // 胶片颗粒（Film Grain）
    // 最终输出（To Screen / Present）


    imageStore(out_texture, pixelCoord, vec4(finalColor, fxaa_result.a));
}
