#version 430 core

#define RADIUS 4
#define GROUP_SIZE 256
#define TILE_SIZE (GROUP_SIZE + 2 * RADIUS)

// 线程组形状转换为纵向列：横向 1 个线程，纵向 256 个线程
layout (local_size_x = 1, local_size_y = GROUP_SIZE, local_size_z = 1) in;

layout (binding = 0, rgba32f) uniform readonly image2D InputImage;  // 第一步的中间输出
layout (binding = 1, rgba32f) uniform writeonly image2D OutputImage; // 最终的模糊结果

const float Weights[RADIUS + 1] = float[](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);

shared vec4 s_Pixels[TILE_SIZE];

void main()
{
    ivec2 texSize = imageSize(InputImage); // 这里获取图片的长宽
    ivec2 centerCoord = ivec2(gl_GlobalInvocationID.xy);
    uint localId = gl_LocalInvocationID.y;
    uint sharedIdx = localId + RADIUS;

    // 加载中心像素
    s_Pixels[sharedIdx] = imageLoad(InputImage, clamp(centerCoord, ivec2(0), texSize - ivec2(1)));

    // 顶部边界填充
    if (localId < RADIUS)
    {
        ivec2 topCoord = ivec2(centerCoord.x, centerCoord.y - RADIUS);
        s_Pixels[localId] = imageLoad(InputImage, clamp(topCoord, ivec2(0), texSize - ivec2(1)));
    }

    // 底部边界填充
    if (localId >= (GROUP_SIZE - RADIUS))
    {
        ivec2 bottomCoord = ivec2(centerCoord.x, centerCoord.y + RADIUS);
        s_Pixels[sharedIdx + RADIUS] = imageLoad(InputImage, clamp(bottomCoord, ivec2(0), texSize - ivec2(1)));
    }

    barrier();
    memoryBarrierShared();

    if (centerCoord.x >= texSize.x || centerCoord.y >= texSize.y)
    return;

    // 垂直方向卷积计算
    vec4 blurredColor = s_Pixels[sharedIdx] * Weights[0];

    for (int i = 1; i <= RADIUS; ++i)
    {
        blurredColor += s_Pixels[sharedIdx - i] * Weights[i];
        blurredColor += s_Pixels[sharedIdx + i] * Weights[i];
    }

    imageStore(OutputImage, centerCoord, blurredColor);
}
