#version 450
#extension GL_GOOGLE_include_directive: enable
#include "global_shader_common.glsl"
#include "common_math.glsl"




#define COMPUTE_BENT_NORMAL 0


layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


layout (set = 2, binding = 0) uniform sampler2D input_texture;
layout(rgba16f, set = 2, binding = 1) uniform image2D output_texture;

#include "geometry.glsl"
//#include "saoImpl.glsl"


void main()
{


    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    // 以 global_SSAO 为输出, 以输出 的 大小,转换出应该采样的 UV
    ivec2 image_size = imageSize(output_texture);
    uint width = uint(image_size.x);
    uint height = uint(image_size.y);
    // 越界检查
    if (x >= width || y >= height) {
        return;
    }
    ivec2 pixelCoord = ivec2(x, y); // imageStore 使用 2D 向量作为坐标
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / image_size;

    highp float depth = sampleDepth(input_texture, inUV, 0.0);
    vec3 origin = get_view_pos(inUV, depth, invProjection);
    vec2 depth_tex_size = textureSize(input_texture, 0);

    vec3 normal = computeViewSpaceNormalHighQ(input_texture, inUV, origin.z, origin, 1 / depth_tex_size,
            invProjection);

    imageStore(output_texture, pixel_coords, vec4(normal, 0.0)); // 纯红
}

