#version 450

#define PNANOVDB_GLSL

#extension GL_GOOGLE_include_directive: enable
#include "global_shader_common.glsl"

layout(std430, binding = 0) readonly buffer NanoVDBBuffer {
    uint pnanovdb_buf_data[];
};

#include "PNanoVDB.h"

// 定义 SSBO 存储 NanoVDB 数据


void main()
{
    // 获取网格句柄（通常在缓冲区的开头）
    //    nanovdb_address_t addr = { 0 }; // 假设网格从偏移量 0 开始
    //    nanovdb_grid_handle_t grid = nanovdb_get_grid(pnvdb.data, addr);


}