#version 450
#extension GL_GOOGLE_include_directive: enable
#include "global_shader_common.glsl"


#define COMPUTE_BENT_NORMAL 0

float saturate(float x) { return clamp(x, 0.0, 1.0); }


#include "geometry.glsl"
//#include "saoImpl.glsl"

layout(set = 2, binding = 0) uniform sampler2D input_depth_texture;
layout(r8, set = 2, binding = 1) uniform image2D output_texture;





highp vec3 computeViewSpaceNormalHighQ_temp(
        const highp sampler2D depthTexture, const highp vec2 uv,
        const highp float depth, const highp vec3 position,
        highp vec2 texel, highp mat4 invProjection) {
    precision highp
    float;

    vec3 pos_c = position;
    highp vec2 dx = vec2(texel.x, 0.0);
    highp vec2 dy = vec2(0.0, texel.y);

    vec4 H;
    H.x = sampleDepth(depthTexture, uv - dx, 0.0);
    H.y = sampleDepth(depthTexture, uv + dx, 0.0);
    H.z = sampleDepth(depthTexture, uv - dx * 2.0, 0.0);
    H.w = sampleDepth(depthTexture, uv + dx * 2.0, 0.0);
    vec2 he = abs((2.0 * H.xy - H.zw) - depth);
    vec3 pos_l = get_view_pos(uv - dx, (H.x), invProjection);
    vec3 pos_r = get_view_pos(uv + dx, (H.y), invProjection);
    vec3 dpdx = (he.x < he.y) ? (pos_c - pos_l) : (pos_r - pos_c);

    vec4 V;
    V.x = sampleDepth(depthTexture, uv - dy, 0.0);
    V.y = sampleDepth(depthTexture, uv + dy, 0.0);
    V.z = sampleDepth(depthTexture, uv - dy * 2.0, 0.0);
    V.w = sampleDepth(depthTexture, uv + dy * 2.0, 0.0);
    vec2 ve = abs((2.0 * V.xy - V.zw) - depth);
    vec3 pos_d = get_view_pos(uv - dy, (V.x), invProjection);
    vec3 pos_u = get_view_pos(uv + dy, (V.y), invProjection);
    vec3 dpdy = (ve.x < ve.y) ? (pos_c - pos_d) : (pos_u - pos_c);

    return normalize(cross(dpdy, dpdx));
}

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main()
{


    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    // 以 global_SSAO 为输出, 以输出 的 大小,转换出应该采样的 UV
    ivec2 texSize = imageSize(output_texture);
    uint width = uint(texSize.x);
    uint height = uint(texSize.y);
    // 越界检查
    if (x >= width || y >= height) {
        return;
    }
    ivec2 pixelCoord = ivec2(x, y); // imageStore 使用 2D 向量作为坐标
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 inUV = (vec2(pixel_coords) + 0.5) / texSize;


    highp float depth = sampleDepth(input_depth_texture, inUV, 0.0);
    vec3 origin = get_view_pos(inUV, depth, invProjection);

    vec2 depth_tex_size = textureSize(input_depth_texture, 0);

    vec3 normal = computeViewSpaceNormalHighQ_temp(input_depth_texture, inUV, viewPos.z, viewPos, 1 / depth_tex_size,
            invProjection);


    float occlusion = 0.0;
    vec3 bentNormal; // will be discarded

    //    scalableAmbientObscurance(occlusion, bentNormal, inUV, origin, normal);


    //    float aoVisibility = pow(saturate(1.0 - occlusion), materialParams.power);
    float aoVisibility = pow(saturate(1.0 - occlusion), 2);



    imageStore(output_texture, pixel_coords, vec4(aoVisibility, 0.0, 0.0, 0.0)); // 纯红
}
