#version 460

// 这里有几个引用,但是呢? 我并不知道文件在哪里
#include "Common.glsl"

// Temporal Anti-Alias
#define LOCAL_SIZE_XY 16
layout (local_size_x = LOCAL_SIZE_XY, local_size_y = LOCAL_SIZE_XY, local_size_z = 1) in;

#define VIEW_DATA_SET 0
#include "ViewData.glsl"

#define FRAME_DATA_SET 2
#include "FrameData.glsl"

layout (set = 1, binding = 0, rgba16f) uniform image2D outHdrColor;
layout (set = 1, binding = 1) uniform sampler2D inDepth;
layout (set = 1, binding = 2) uniform sampler2D inHistory;
layout (set = 1, binding = 3) uniform sampler2D inVelocity;
layout (set = 1, binding = 4) uniform sampler2D inHdrColor;

struct TAAPushConstant
{
    uint firstRender;
    uint camMove;
};

layout(push_constant) uniform block
{
    TAAPushConstant pushConstant;
};

bool IsFirstFrame()
{
    return pushConstant.firstRender != 0;
}

bool IsCamMove()
{
    return pushConstant.camMove != 0;
}

// TAA random offset within one pixel range.
// so use 3x3 tap to get safe value.
const ivec2 kPattern3x3[9] = {
ivec2(-1,-1),
ivec2(-1, 0),
ivec2(-1, 1),
ivec2( 0, 1),
ivec2( 0, 0),
ivec2( 0,-1),
ivec2( 1, 1),
ivec2( 1, 0),
ivec2( 1,-1)
};
const float kRpc9 = 1.0f / 9.0f;

// keep 1 pixel border for lds, to keep edge tap safe.
const int kBorderSize = 1;
const int kGroupSize  = LOCAL_SIZE_XY;
const int kLdsLength  = kGroupSize + kBorderSize * 2;
const int kLdsArea    = kLdsLength * kLdsLength;

const float kTinyFloat   = 1e-8f;
const float kMaxFloat16  = 32767.0f;
const float kMaxFloat16u = 65535.0f;

shared vec3  sharedColor[kLdsLength][kLdsLength];
shared float sharedDepth[kLdsLength][kLdsLength];

vec3 reinhard(vec3 hdr)
{
    return hdr / (hdr + 1.0f);
}

vec3 reinhardInverse(in vec3 sdr)
{
    return sdr / max(1.0f - sdr, 1e-5f);
}

vec3 ldsLoadColor(ivec2 GId)
{
    GId += ivec2(kBorderSize);
    return sharedColor[GId.x][GId.y];
}

// store color with reinhard tonemmaper.
void ldsStoreColor(ivec2 GId, vec3 color)
{
    sharedColor[GId.x][GId.y] = reinhard(color);
}

float ldsLoadDepth(ivec2 GId)
{
    GId += ivec2(kBorderSize);
    return sharedDepth[GId.x][GId.y];
}

void ldsStoreDepth(ivec2 GId, float depth)
{
    sharedDepth[GId.x][GId.y] = depth;
}

float luminance(vec3 color)
{
    return max(dot(color, vec3(0.299f, 0.587f, 0.114f)), 1e-5f);
}

void storeColorDepth(ivec2 GId, ivec2 TId, ivec2 size)
{
    TId = clamp(TId, ivec2(0,0), size - ivec2(1,1));

    // store color.
    ldsStoreColor(GId, texelFetch(inHdrColor, TId, 0).rgb);

    // store linear z.
    float linearZ = linearizeDepth(texelFetch(inDepth, TId, 0).r, viewData.camInfo.z, viewData.camInfo.w);
    ldsStoreDepth(GId, linearZ);
}

void prepareLds(ivec2 topLeft, ivec2 workSize, int groupIndex)
{
    // 4 sample per pixel.
    if(groupIndex < (kLdsArea >> 2)) // 1 / 4 area pixel work.
    {
        // sample [0, 0]
        ivec2 id0 = ivec2(
                groupIndex                     % kLdsLength,
                groupIndex                     / kLdsLength);
        storeColorDepth(id0, topLeft + id0, workSize);

        // sample [0.25,  0.25]
        ivec2 id1 = ivec2(
                (groupIndex + (kLdsArea >> 2))  % kLdsLength,
                (groupIndex + (kLdsArea >> 2))  / kLdsLength);
        storeColorDepth(id1, topLeft + id1, workSize);

        // sample [0.5, 0.5]
        ivec2 id2 = ivec2(
                (groupIndex + (kLdsArea >> 1))  % kLdsLength,
                (groupIndex + (kLdsArea >> 1))  / kLdsLength);
        storeColorDepth(id2, topLeft + id2, workSize);

        // sample [0.75, 0.75]
        ivec2 id3 = ivec2(
                (groupIndex + kLdsArea * 3 / 4) % kLdsLength,
                (groupIndex + kLdsArea * 3 / 4) / kLdsLength);
        storeColorDepth(id3, topLeft + id3, workSize);
    }
}

// linear z cloest test.
void depthGetClosest(ivec2 pos, inout float cloestDepth, inout ivec2 cloestPos)
{
    float d = ldsLoadDepth(pos);

    if(d < cloestDepth)
    {
        cloestDepth = d;
        cloestPos = pos;
    }
}

// 3x3 tap get closet pos depth.
float velocitySample3x3Closest(ivec2 groupPos, ivec2 topLeft, out vec2 velocity)
{
    float minDepth = 1.0f;
    ivec2 minPos   = groupPos;

    depthGetClosest(groupPos + kPattern3x3[0], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[1], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[2], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[3], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[4], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[5], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[6], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[7], minDepth, minPos);
    depthGetClosest(groupPos + kPattern3x3[8], minDepth, minPos);

    velocity = texelFetch(inVelocity, topLeft + minPos, 0).xy;

    return minDepth;
}

// catmull Rom 9 tap sampler.
// sTex: linear clamp sampler2D.
// uv: sample uv.
// resolution: working rt resolution.
vec3 catmullRom9Sample(sampler2D sTex, vec2 uv, vec2 resolution)
{
    vec2 samplePos = uv * resolution;
    vec2 texPos1   = floor(samplePos - 0.5f) + 0.5f;

    vec2 f = samplePos - texPos1;

    vec2 w0 = f * (-0.5f + f * (1.0f - 0.5f * f));
    vec2 w1 = 1.0f + f * f * (-2.5f + 1.5f * f);
    vec2 w2 = f * (0.5f + f * (2.0f - 1.5f * f));
    vec2 w3 = f * f * (-0.5f + 0.5f * f);

    vec2 w12 = w1 + w2;
    vec2 offset12 = w2 / (w1 + w2);

    vec2 texPos0 = texPos1 - 1.0f;
    vec2 texPos3 = texPos1 + 2.0f;

    vec2 texPos12 = texPos1 + offset12;

    texPos0  /= resolution;
    texPos3  /= resolution;
    texPos12 /= resolution;

    vec3 result = vec3(0.0f);

    result += textureLod(sTex, vec2(texPos0.x,  texPos0.y),  0).xyz * w0.x  * w0.y;
    result += textureLod(sTex, vec2(texPos12.x, texPos0.y),  0).xyz * w12.x * w0.y;
    result += textureLod(sTex, vec2(texPos3.x,  texPos0.y),  0).xyz * w3.x  * w0.y;

    result += textureLod(sTex, vec2(texPos0.x,  texPos12.y), 0).xyz * w0.x  * w12.y;
    result += textureLod(sTex, vec2(texPos12.x, texPos12.y), 0).xyz * w12.x * w12.y;
    result += textureLod(sTex, vec2(texPos3.x,  texPos12.y), 0).xyz * w3.x  * w12.y;

    result += textureLod(sTex, vec2(texPos0.x,  texPos3.y),  0).xyz * w0.x  * w3.y;
    result += textureLod(sTex, vec2(texPos12.x, texPos3.y),  0).xyz * w12.x * w3.y;
    result += textureLod(sTex, vec2(texPos3.x,  texPos3.y),  0).xyz * w3.x  * w3.y;

    return max(result, vec3(0.0f));
}

void main()
{
    ivec2 workSize = textureSize(inHdrColor, 0).xy;
    ivec2 topLeft  = ivec2(gl_WorkGroupID.xy) * kGroupSize - kBorderSize;
    ivec2 groupPos = ivec2(gl_LocalInvocationID.xy);
    int groupIndex = int(gl_LocalInvocationIndex);

    prepareLds(topLeft, workSize, groupIndex);

    groupMemoryBarrier();
    barrier();

    ivec2 pixelPos = ivec2(gl_GlobalInvocationID.xy);
    if (pixelPos.x >= workSize.x || pixelPos.y >= workSize.y)
    {
        return;
    }

    vec2 texelSize = 1.0f / vec2(workSize);
    vec2 uv        = (vec2(pixelPos) + vec2(0.5)) * texelSize;

    // get cloest velocity.
    vec2 velocity;
    const float cloestDepth = velocitySample3x3Closest(groupPos, topLeft, velocity);
    const bool  bSky = cloestDepth <= BG_DEPTH;

    // reproject uv.
    vec2 reprojectedUV = uv - velocity;

    float velocityLerp = 0.0f;
    if(!IsFirstFrame())
    {
        velocityLerp = texture(inHistory, reprojectedUV).w;
    }

    const float ideaStaticBoxSize = 2.5f;
    float staticBoxSize = IsCamMove() ? ideaStaticBoxSize : mix(0.5f, ideaStaticBoxSize, velocityLerp);
    float boxSize = mix(0.5f, staticBoxSize, bSky ? 0.0f : smoothstep(0.02f, 0.0f, length(velocity)));

    // in center color.
    vec3 colorIn = ldsLoadColor(groupPos);

    // sample history color.
    vec3 colorHistory = catmullRom9Sample(inHistory, reprojectedUV, vec2(workSize));
    colorHistory = reinhard(colorHistory);

    // variance clamp.
    vec3 clampHistory;
    {
        float wsum = 0.0f;
        vec3 vsum  = vec3(0.0f, 0.0f, 0.0f);
        vec3 vsum2 = vec3(0.0f, 0.0f, 0.0f);

        for (int y = -1; y <= 1; ++y)
        {
            for (int x = -1; x <= 1; ++x)
            {
                const vec3 neigh = ldsLoadColor(groupPos + ivec2(x, y));
                const float w = exp(-0.75f * (x * x + y * y));

                vsum2 += neigh * neigh * w;
                vsum  += neigh * w;
                wsum  += w;
            }
        }

        const vec3 ex  = vsum / wsum;
        const vec3 ex2 = vsum2 / wsum;
        const vec3 dev = sqrt(max(ex2 - ex * ex, 0.0f));

        vec3 nmin = ex - dev * boxSize;
        vec3 nmax = ex + dev * boxSize;
        clampHistory = clamp(colorHistory, nmin, nmax);
    }

    // when camera move, use this.
    // when camera don't move, use more bigger blend factor if motion factor check.
    const float ideaLerpFactor = 0.01f;
    float blendFactor = ideaLerpFactor;
    {
        const float threshold   = 0.5f;
        const float base        = 0.5f;
        const float gather      = 0.1666f;

        // subpixel flicker reduce
        float depth = linearizeDepth(cloestDepth, viewData.camInfo.z, viewData.camInfo.w);
        float texelVelMag    = length(velocity * vec2(workSize)) * depth;
        float subpixelMotion = clamp(threshold / (texelVelMag + kTinyFloat), 0.0f, 1.0f);

        // something moveing
        float dynamicBlendFactor = texelVelMag * base + subpixelMotion * gather;

        // lumiance bias correct.
        float luminanceHistory = luminance(clampHistory);
        float luminanceCurrent = luminance(colorIn);
        float unbiasedDifference = abs(luminanceCurrent - luminanceHistory) / ((max(luminanceCurrent, luminanceHistory) + 0.3));
        dynamicBlendFactor *= 1.0 - unbiasedDifference;

        // clamp
        dynamicBlendFactor = clamp(dynamicBlendFactor, 0.0f, 0.4f);

        float lerpFactor = length(velocity * vec2(workSize)) * 5.0f;
        lerpFactor  = clamp(lerpFactor, 0, 1);

        blendFactor = bSky ? blendFactor : mix(blendFactor, dynamicBlendFactor, lerpFactor);

        // tiny move, so reset lerp factor.
        velocityLerp = lerpFactor > 0.01f ? 0 : velocityLerp;

        // mix lerp factor by frames to get a good clip value.
        velocityLerp = mix(velocityLerp, 1.0f, ideaLerpFactor);
    }

    vec3 colorResolve = mix(clampHistory, colorIn, blendFactor);

    // half16 safe clamp.
    colorResolve = min(vec3(65504.0f), colorResolve);

    imageStore(outHdrColor, ivec2(gl_GlobalInvocationID.xy), vec4(colorResolve, velocityLerp));
}